spring:
  application:
    name: remna-shop
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      auto-commit=false
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql:
      properties:
        hibernate:
          format_sql: true

app:
  vpn:
    test-period:
      duration: PT24H
      traffic-limit-bytes: 1073741824
  jwt:
    secret: ${JWT_SECRET}
    expiration: PT1H

integration:
  remnawave:
    base-url: ${REMNAWAVE_URL}
    api-key: ${REMNAWAVE_API_KEY}

logging:
  level:
    org.springframework.security: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE