spring:
  application:
    name: remnashop
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  jackson:
    property-naming-strategy: SNAKE_CASE
app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: PT1H

integration:
  remnawave:
    base-url: ${REMNAWAVE_URL}
    api-key: ${REMNAWAVE_API_KEY}

logging:
  level:
    org.springframework.security: TRACE
springdoc:
    default-consumes-media-type: application/json
    default-produces-media-type: application/json