spring:
  application:
    name: remnashop
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  sql:
    init:
      mode: always
      platform: postgresql  # picks up schema-postgresql.sql instead
      continue-on-error: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  jackson:
    property-naming-strategy: SNAKE_CASE
remnashop:
  jwt:
    secret: ${JWT_SECRET}
    expiration: PT1H
  superuser:
    username: ${SUPERUSER_USERNAME}
    password: ${SUPERUSER_PASSWORD}
    email: ${SUPERUSER_EMAIL}
  integration:
    remnawave:
      base-url: ${REMNAWAVE_URL}
      api-key: ${REMNAWAVE_API_KEY}

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.web.client: TRACE
springdoc:
    default-consumes-media-type: application/json
    default-produces-media-type: application/json