package bruchalex.remna_shop.vpn_profile.core.domain;

import java.util.List;

public class VpnProfile {
    private String userId; // taken from User
    private String username; // users can define
    private String vpnProfileUuid; // generated by integration
    private Integer maxDevicesAllowed;
    private List<Device> devices;
    private String subscriptionUrl;
    private String telegramId; // users can define
    private String label; // users can define
    private String createdAt;
    private String updatedAt;

    public List<Device> removeDevice(String deviceId) {
        if (devices.isEmpty()) {
            throw new IllegalStateException("No devices to remove");
        }

        devices.removeIf(device -> device.getDeviceId().equals(deviceId));
        return devices;
    }
}
